# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eamviewer.ui'
#
# Created by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EAMViewer(object):
    def setupUi(self, EAMViewer):
        EAMViewer.setObjectName(_fromUtf8("EAMViewer"))
        EAMViewer.resize(1056, 1065)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EAMViewer.sizePolicy().hasHeightForWidth())
        EAMViewer.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(EAMViewer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tbColorImage = QtGui.QWidget()
        self.tbColorImage.setObjectName(_fromUtf8("tbColorImage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tbColorImage)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gVColorImg = EventsQGraphicsView(self.tbColorImage)
        self.gVColorImg.setObjectName(_fromUtf8("gVColorImg"))
        self.verticalLayout_6.addWidget(self.gVColorImg)
        self.tabWidget.addTab(self.tbColorImage, _fromUtf8(""))
        self.tbCurrentROI = QtGui.QWidget()
        self.tbCurrentROI.setObjectName(_fromUtf8("tbCurrentROI"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tbCurrentROI)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gVROIHist = QtGui.QGraphicsView(self.tbCurrentROI)
        self.gVROIHist.setObjectName(_fromUtf8("gVROIHist"))
        self.gridLayout_3.addWidget(self.gVROIHist, 1, 1, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pbToROI = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToROI.setObjectName(_fromUtf8("pbToROI"))
        self.gridLayout_6.addWidget(self.pbToROI, 0, 0, 1, 2)
        self.pbToLines = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToLines.setObjectName(_fromUtf8("pbToLines"))
        self.gridLayout_6.addWidget(self.pbToLines, 2, 0, 1, 2)
        self.pbToCircles = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToCircles.setObjectName(_fromUtf8("pbToCircles"))
        self.gridLayout_6.addWidget(self.pbToCircles, 3, 0, 1, 2)
        self.leROIName = QtGui.QLineEdit(self.tbCurrentROI)
        self.leROIName.setObjectName(_fromUtf8("leROIName"))
        self.gridLayout_6.addWidget(self.leROIName, 6, 1, 1, 1)
        self.pbToDB = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToDB.setObjectName(_fromUtf8("pbToDB"))
        self.gridLayout_6.addWidget(self.pbToDB, 8, 0, 1, 2)
        self.pbToCorners = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToCorners.setObjectName(_fromUtf8("pbToCorners"))
        self.gridLayout_6.addWidget(self.pbToCorners, 4, 0, 1, 2)
        self.label = QtGui.QLabel(self.tbCurrentROI)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 6, 0, 1, 1)
        self.pbToCanny = QtGui.QPushButton(self.tbCurrentROI)
        self.pbToCanny.setObjectName(_fromUtf8("pbToCanny"))
        self.gridLayout_6.addWidget(self.pbToCanny, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 5, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gVROI = QtGui.QGraphicsView(self.tbCurrentROI)
        self.gVROI.setObjectName(_fromUtf8("gVROI"))
        self.gridLayout_3.addWidget(self.gVROI, 0, 0, 2, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_3.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tbCurrentROI, _fromUtf8(""))
        self.tbROIDataBase = QtGui.QWidget()
        self.tbROIDataBase.setObjectName(_fromUtf8("tbROIDataBase"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tbROIDataBase)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.tbROIDataBase)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 86, 16))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tbROIDataBase, _fromUtf8(""))
        self.tbGrayImage = QtGui.QWidget()
        self.tbGrayImage.setObjectName(_fromUtf8("tbGrayImage"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tbGrayImage)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gVGrayImg = EventsQGraphicsView(self.tbGrayImage)
        self.gVGrayImg.setObjectName(_fromUtf8("gVGrayImg"))
        self.verticalLayout_5.addWidget(self.gVGrayImg)
        self.tabWidget.addTab(self.tbGrayImage, _fromUtf8(""))
        self.tbProcGrayImage = QtGui.QWidget()
        self.tbProcGrayImage.setObjectName(_fromUtf8("tbProcGrayImage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tbProcGrayImage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gVProcGrayImg = EventsQGraphicsView(self.tbProcGrayImage)
        self.gVProcGrayImg.setObjectName(_fromUtf8("gVProcGrayImg"))
        self.verticalLayout.addWidget(self.gVProcGrayImg)
        self.tabWidget.addTab(self.tbProcGrayImage, _fromUtf8(""))
        self.tbGrayHist = QtGui.QWidget()
        self.tbGrayHist.setObjectName(_fromUtf8("tbGrayHist"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tbGrayHist)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gVGrayHist = EventsQGraphicsView(self.tbGrayHist)
        self.gVGrayHist.setObjectName(_fromUtf8("gVGrayHist"))
        self.verticalLayout_2.addWidget(self.gVGrayHist)
        self.tabWidget.addTab(self.tbGrayHist, _fromUtf8(""))
        self.tbProcColorImage = QtGui.QWidget()
        self.tbProcColorImage.setObjectName(_fromUtf8("tbProcColorImage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tbProcColorImage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gVProcColorImg = EventsQGraphicsView(self.tbProcColorImage)
        self.gVProcColorImg.setObjectName(_fromUtf8("gVProcColorImg"))
        self.verticalLayout_3.addWidget(self.gVProcColorImg)
        self.tabWidget.addTab(self.tbProcColorImage, _fromUtf8(""))
        self.tbTemplate = QtGui.QWidget()
        self.tbTemplate.setObjectName(_fromUtf8("tbTemplate"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tbTemplate)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.cBxMode = QtGui.QComboBox(self.tbTemplate)
        self.cBxMode.setObjectName(_fromUtf8("cBxMode"))
        self.cBxMode.addItem(_fromUtf8(""))
        self.cBxMode.addItem(_fromUtf8(""))
        self.cBxMode.addItem(_fromUtf8(""))
        self.cBxMode.addItem(_fromUtf8(""))
        self.cBxMode.addItem(_fromUtf8(""))
        self.cBxMode.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cBxMode, 0, 1, 1, 1)
        self.qualitySlider = QtGui.QSlider(self.tbTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualitySlider.sizePolicy().hasHeightForWidth())
        self.qualitySlider.setSizePolicy(sizePolicy)
        self.qualitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.qualitySlider.setObjectName(_fromUtf8("qualitySlider"))
        self.gridLayout_5.addWidget(self.qualitySlider, 0, 4, 1, 1)
        self.scrollArea2 = QtGui.QScrollArea(self.tbTemplate)
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName(_fromUtf8("scrollArea2"))
        self.scrollAreaWidgetContents2 = QtGui.QWidget()
        self.scrollAreaWidgetContents2.setGeometry(QtCore.QRect(0, 0, 1026, 750))
        self.scrollAreaWidgetContents2.setObjectName(_fromUtf8("scrollAreaWidgetContents2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea2.setWidget(self.scrollAreaWidgetContents2)
        self.gridLayout_5.addWidget(self.scrollArea2, 1, 0, 1, 10)
        self.label_2 = QtGui.QLabel(self.tbTemplate)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 8, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.tbTemplate)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tbTemplate, _fromUtf8(""))
        self.tbColorHist = QtGui.QWidget()
        self.tbColorHist.setObjectName(_fromUtf8("tbColorHist"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tbColorHist)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gVColorHist = EventsQGraphicsView(self.tbColorHist)
        self.gVColorHist.setObjectName(_fromUtf8("gVColorHist"))
        self.verticalLayout_4.addWidget(self.gVColorHist)
        self.tabWidget.addTab(self.tbColorHist, _fromUtf8(""))
        self.tbCamera = QtGui.QWidget()
        self.tbCamera.setObjectName(_fromUtf8("tbCamera"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tbCamera)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pbPlay = QtGui.QPushButton(self.tbCamera)
        self.pbPlay.setObjectName(_fromUtf8("pbPlay"))
        self.gridLayout_7.addWidget(self.pbPlay, 0, 0, 1, 1)
        self.pbRecord = QtGui.QPushButton(self.tbCamera)
        self.pbRecord.setObjectName(_fromUtf8("pbRecord"))
        self.gridLayout_7.addWidget(self.pbRecord, 0, 1, 1, 1)
        self.pbChooseFrame = QtGui.QPushButton(self.tbCamera)
        self.pbChooseFrame.setObjectName(_fromUtf8("pbChooseFrame"))
        self.gridLayout_7.addWidget(self.pbChooseFrame, 0, 2, 1, 1)
        self.lblFPS = QtGui.QLabel(self.tbCamera)
        self.lblFPS.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFPS.setObjectName(_fromUtf8("lblFPS"))
        self.gridLayout_7.addWidget(self.lblFPS, 0, 4, 1, 1)
        self.sliderFPS = QtGui.QSlider(self.tbCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderFPS.sizePolicy().hasHeightForWidth())
        self.sliderFPS.setSizePolicy(sizePolicy)
        self.sliderFPS.setMinimum(1)
        self.sliderFPS.setMaximum(33)
        self.sliderFPS.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFPS.setObjectName(_fromUtf8("sliderFPS"))
        self.gridLayout_7.addWidget(self.sliderFPS, 0, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 3, 1, 1)
        self.pbPopFromToolchain = QtGui.QPushButton(self.tbCamera)
        self.pbPopFromToolchain.setObjectName(_fromUtf8("pbPopFromToolchain"))
        self.gridLayout_7.addWidget(self.pbPopFromToolchain, 3, 4, 1, 2)
        self.lblOrig = QtGui.QLabel(self.tbCamera)
        self.lblOrig.setText(_fromUtf8(""))
        self.lblOrig.setObjectName(_fromUtf8("lblOrig"))
        self.gridLayout_7.addWidget(self.lblOrig, 1, 0, 3, 3)
        self.textEditVideo = QtGui.QTextEdit(self.tbCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditVideo.sizePolicy().hasHeightForWidth())
        self.textEditVideo.setSizePolicy(sizePolicy)
        self.textEditVideo.setReadOnly(True)
        self.textEditVideo.setObjectName(_fromUtf8("textEditVideo"))
        self.gridLayout_7.addWidget(self.textEditVideo, 2, 3, 1, 3)
        self.tabWidget.addTab(self.tbCamera, _fromUtf8(""))
        self.tbOverview = QtGui.QWidget()
        self.tbOverview.setObjectName(_fromUtf8("tbOverview"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tbOverview)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gV_6 = EventsQGraphicsView(self.tbOverview)
        self.gV_6.setObjectName(_fromUtf8("gV_6"))
        self.gridLayout_2.addWidget(self.gV_6, 3, 2, 1, 1)
        self.gV_5 = EventsQGraphicsView(self.tbOverview)
        self.gV_5.setObjectName(_fromUtf8("gV_5"))
        self.gridLayout_2.addWidget(self.gV_5, 3, 1, 1, 1)
        self.gV_2 = EventsQGraphicsView(self.tbOverview)
        self.gV_2.setObjectName(_fromUtf8("gV_2"))
        self.gridLayout_2.addWidget(self.gV_2, 1, 3, 1, 1)
        self.gV_3 = EventsQGraphicsView(self.tbOverview)
        self.gV_3.setObjectName(_fromUtf8("gV_3"))
        self.gridLayout_2.addWidget(self.gV_3, 2, 3, 1, 1)
        self.gV_7 = EventsQGraphicsView(self.tbOverview)
        self.gV_7.setObjectName(_fromUtf8("gV_7"))
        self.gridLayout_2.addWidget(self.gV_7, 3, 3, 1, 1)
        self.gV_1 = EventsQGraphicsView(self.tbOverview)
        self.gV_1.setObjectName(_fromUtf8("gV_1"))
        self.gridLayout_2.addWidget(self.gV_1, 0, 3, 1, 1)
        self.gV_4 = EventsQGraphicsView(self.tbOverview)
        self.gV_4.setObjectName(_fromUtf8("gV_4"))
        self.gridLayout_2.addWidget(self.gV_4, 3, 0, 1, 1)
        self.gV_0 = EventsQGraphicsView(self.tbOverview)
        self.gV_0.setObjectName(_fromUtf8("gV_0"))
        self.gridLayout_2.addWidget(self.gV_0, 0, 0, 3, 3)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(1, 5)
        self.gridLayout_2.setRowStretch(2, 5)
        self.gridLayout_2.setRowStretch(3, 5)
        self.tabWidget.addTab(self.tbOverview, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 20)
        EAMViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EAMViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuStandard = QtGui.QMenu(self.menubar)
        self.menuStandard.setObjectName(_fromUtf8("menuStandard"))
        self.menuFilter = QtGui.QMenu(self.menubar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuStructures = QtGui.QMenu(self.menubar)
        self.menuStructures.setObjectName(_fromUtf8("menuStructures"))
        self.menuROI = QtGui.QMenu(self.menubar)
        self.menuROI.setObjectName(_fromUtf8("menuROI"))
        self.menuDatabase = QtGui.QMenu(self.menuROI)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuTemplate_matching = QtGui.QMenu(self.menuROI)
        self.menuTemplate_matching.setObjectName(_fromUtf8("menuTemplate_matching"))
        EAMViewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EAMViewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        EAMViewer.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(EAMViewer)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(EAMViewer)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionReset_data = QtGui.QAction(EAMViewer)
        self.actionReset_data.setObjectName(_fromUtf8("actionReset_data"))
        self.actionLast_setting = QtGui.QAction(EAMViewer)
        self.actionLast_setting.setObjectName(_fromUtf8("actionLast_setting"))
        self.actionInversion = QtGui.QAction(EAMViewer)
        self.actionInversion.setObjectName(_fromUtf8("actionInversion"))
        self.actionHistogram_equalization = QtGui.QAction(EAMViewer)
        self.actionHistogram_equalization.setObjectName(_fromUtf8("actionHistogram_equalization"))
        self.actionLinear_transformation = QtGui.QAction(EAMViewer)
        self.actionLinear_transformation.setObjectName(_fromUtf8("actionLinear_transformation"))
        self.actionGamma_transformation = QtGui.QAction(EAMViewer)
        self.actionGamma_transformation.setObjectName(_fromUtf8("actionGamma_transformation"))
        self.actionThreshold = QtGui.QAction(EAMViewer)
        self.actionThreshold.setObjectName(_fromUtf8("actionThreshold"))
        self.actionAdaptive_threshold = QtGui.QAction(EAMViewer)
        self.actionAdaptive_threshold.setObjectName(_fromUtf8("actionAdaptive_threshold"))
        self.actionMean = QtGui.QAction(EAMViewer)
        self.actionMean.setObjectName(_fromUtf8("actionMean"))
        self.actionMedian = QtGui.QAction(EAMViewer)
        self.actionMedian.setObjectName(_fromUtf8("actionMedian"))
        self.actionGaussian = QtGui.QAction(EAMViewer)
        self.actionGaussian.setObjectName(_fromUtf8("actionGaussian"))
        self.actionSobel = QtGui.QAction(EAMViewer)
        self.actionSobel.setObjectName(_fromUtf8("actionSobel"))
        self.actionScharr = QtGui.QAction(EAMViewer)
        self.actionScharr.setObjectName(_fromUtf8("actionScharr"))
        self.actionCanny = QtGui.QAction(EAMViewer)
        self.actionCanny.setObjectName(_fromUtf8("actionCanny"))
        self.actionSmall_custom_filter = QtGui.QAction(EAMViewer)
        self.actionSmall_custom_filter.setObjectName(_fromUtf8("actionSmall_custom_filter"))
        self.actionDilate = QtGui.QAction(EAMViewer)
        self.actionDilate.setObjectName(_fromUtf8("actionDilate"))
        self.actionErode = QtGui.QAction(EAMViewer)
        self.actionErode.setObjectName(_fromUtf8("actionErode"))
        self.actionMorphology_filter = QtGui.QAction(EAMViewer)
        self.actionMorphology_filter.setObjectName(_fromUtf8("actionMorphology_filter"))
        self.actionLaplacian = QtGui.QAction(EAMViewer)
        self.actionLaplacian.setObjectName(_fromUtf8("actionLaplacian"))
        self.actionLines = QtGui.QAction(EAMViewer)
        self.actionLines.setObjectName(_fromUtf8("actionLines"))
        self.actionCircles = QtGui.QAction(EAMViewer)
        self.actionCircles.setObjectName(_fromUtf8("actionCircles"))
        self.actionCorners = QtGui.QAction(EAMViewer)
        self.actionCorners.setObjectName(_fromUtf8("actionCorners"))
        self.actionSelect = QtGui.QAction(EAMViewer)
        self.actionSelect.setObjectName(_fromUtf8("actionSelect"))
        self.actionOpen = QtGui.QAction(EAMViewer)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionDelete_chosen_elements = QtGui.QAction(EAMViewer)
        self.actionDelete_chosen_elements.setObjectName(_fromUtf8("actionDelete_chosen_elements"))
        self.actionSave_database = QtGui.QAction(EAMViewer)
        self.actionSave_database.setObjectName(_fromUtf8("actionSave_database"))
        self.actionOn_ROI = QtGui.QAction(EAMViewer)
        self.actionOn_ROI.setObjectName(_fromUtf8("actionOn_ROI"))
        self.actionOn_canny = QtGui.QAction(EAMViewer)
        self.actionOn_canny.setObjectName(_fromUtf8("actionOn_canny"))
        self.actionOpen_tm_tab = QtGui.QAction(EAMViewer)
        self.actionOpen_tm_tab.setObjectName(_fromUtf8("actionOpen_tm_tab"))
        self.actionOpen_cam = QtGui.QAction(EAMViewer)
        self.actionOpen_cam.setObjectName(_fromUtf8("actionOpen_cam"))
        self.actionOn_video = QtGui.QAction(EAMViewer)
        self.actionOn_video.setObjectName(_fromUtf8("actionOn_video"))
        self.menuData.addAction(self.actionLoad)
        self.menuData.addAction(self.actionSave)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionReset_data)
        self.menuData.addAction(self.actionLast_setting)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionOpen_cam)
        self.menuStandard.addAction(self.actionInversion)
        self.menuStandard.addAction(self.actionHistogram_equalization)
        self.menuStandard.addAction(self.actionLinear_transformation)
        self.menuStandard.addAction(self.actionGamma_transformation)
        self.menuStandard.addSeparator()
        self.menuStandard.addAction(self.actionThreshold)
        self.menuStandard.addAction(self.actionAdaptive_threshold)
        self.menuFilter.addAction(self.actionMean)
        self.menuFilter.addAction(self.actionMedian)
        self.menuFilter.addAction(self.actionGaussian)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.actionSobel)
        self.menuFilter.addAction(self.actionLaplacian)
        self.menuFilter.addAction(self.actionScharr)
        self.menuFilter.addAction(self.actionCanny)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.actionSmall_custom_filter)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.actionDilate)
        self.menuFilter.addAction(self.actionErode)
        self.menuFilter.addAction(self.actionMorphology_filter)
        self.menuStructures.addAction(self.actionLines)
        self.menuStructures.addAction(self.actionCircles)
        self.menuStructures.addAction(self.actionCorners)
        self.menuDatabase.addAction(self.actionOpen)
        self.menuDatabase.addAction(self.actionDelete_chosen_elements)
        self.menuDatabase.addAction(self.actionSave_database)
        self.menuTemplate_matching.addAction(self.actionOpen_tm_tab)
        self.menuTemplate_matching.addAction(self.actionOn_ROI)
        self.menuTemplate_matching.addAction(self.actionOn_canny)
        self.menuTemplate_matching.addSeparator()
        self.menuTemplate_matching.addAction(self.actionOn_video)
        self.menuROI.addAction(self.actionSelect)
        self.menuROI.addAction(self.menuDatabase.menuAction())
        self.menuROI.addAction(self.menuTemplate_matching.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuStandard.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuStructures.menuAction())
        self.menubar.addAction(self.menuROI.menuAction())

        self.retranslateUi(EAMViewer)
        self.tabWidget.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(EAMViewer)

    def retranslateUi(self, EAMViewer):
        EAMViewer.setWindowTitle(_translate("EAMViewer", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbColorImage), _translate("EAMViewer", "color image", None))
        self.pbToROI.setText(_translate("EAMViewer", "save roi", None))
        self.pbToLines.setText(_translate("EAMViewer", "save lines", None))
        self.pbToCircles.setText(_translate("EAMViewer", "save circles", None))
        self.pbToDB.setText(_translate("EAMViewer", "to database", None))
        self.pbToCorners.setText(_translate("EAMViewer", "save corners", None))
        self.label.setText(_translate("EAMViewer", "name: ", None))
        self.pbToCanny.setText(_translate("EAMViewer", "save canny", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbCurrentROI), _translate("EAMViewer", "current roi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbROIDataBase), _translate("EAMViewer", "roi database", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbGrayImage), _translate("EAMViewer", "gray image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbProcGrayImage), _translate("EAMViewer", "processed gray", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbGrayHist), _translate("EAMViewer", "gray histogram", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbProcColorImage), _translate("EAMViewer", "processed color", None))
        self.cBxMode.setItemText(0, _translate("EAMViewer", "sq_diff", None))
        self.cBxMode.setItemText(1, _translate("EAMViewer", "sq_diff_normed", None))
        self.cBxMode.setItemText(2, _translate("EAMViewer", "ccorr", None))
        self.cBxMode.setItemText(3, _translate("EAMViewer", "ccorr_normed", None))
        self.cBxMode.setItemText(4, _translate("EAMViewer", "ccoeff", None))
        self.cBxMode.setItemText(5, _translate("EAMViewer", "ccoeff_normed", None))
        self.label_2.setText(_translate("EAMViewer", "mode", None))
        self.label_3.setText(_translate("EAMViewer", "quality", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbTemplate), _translate("EAMViewer", "template matching", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbColorHist), _translate("EAMViewer", "color histogram", None))
        self.pbPlay.setText(_translate("EAMViewer", ">", None))
        self.pbRecord.setText(_translate("EAMViewer", "[]", None))
        self.pbChooseFrame.setText(_translate("EAMViewer", "choose frame", None))
        self.lblFPS.setText(_translate("EAMViewer", "fps/s:", None))
        self.pbPopFromToolchain.setText(_translate("EAMViewer", "pop from toolchain", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbCamera), _translate("EAMViewer", "camera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbOverview), _translate("EAMViewer", "image overview", None))
        self.menuData.setTitle(_translate("EAMViewer", "data", None))
        self.menuStandard.setTitle(_translate("EAMViewer", "standard", None))
        self.menuFilter.setTitle(_translate("EAMViewer", "filter", None))
        self.menuStructures.setTitle(_translate("EAMViewer", "structures", None))
        self.menuROI.setTitle(_translate("EAMViewer", "ROI", None))
        self.menuDatabase.setTitle(_translate("EAMViewer", "database", None))
        self.menuTemplate_matching.setTitle(_translate("EAMViewer", "template matching", None))
        self.actionLoad.setText(_translate("EAMViewer", "load", None))
        self.actionSave.setText(_translate("EAMViewer", "save", None))
        self.actionReset_data.setText(_translate("EAMViewer", "reset data", None))
        self.actionLast_setting.setText(_translate("EAMViewer", "last setting", None))
        self.actionInversion.setText(_translate("EAMViewer", "inversion", None))
        self.actionHistogram_equalization.setText(_translate("EAMViewer", "histogram equalization", None))
        self.actionLinear_transformation.setText(_translate("EAMViewer", "linear transformation", None))
        self.actionGamma_transformation.setText(_translate("EAMViewer", "gamma transformation", None))
        self.actionThreshold.setText(_translate("EAMViewer", "threshold", None))
        self.actionAdaptive_threshold.setText(_translate("EAMViewer", "adaptive threshold", None))
        self.actionMean.setText(_translate("EAMViewer", "mean", None))
        self.actionMedian.setText(_translate("EAMViewer", "median", None))
        self.actionGaussian.setText(_translate("EAMViewer", "gaussian", None))
        self.actionSobel.setText(_translate("EAMViewer", "sobel", None))
        self.actionScharr.setText(_translate("EAMViewer", "scharr", None))
        self.actionCanny.setText(_translate("EAMViewer", "canny", None))
        self.actionSmall_custom_filter.setText(_translate("EAMViewer", "small custom filter", None))
        self.actionDilate.setText(_translate("EAMViewer", "dilate", None))
        self.actionErode.setText(_translate("EAMViewer", "erode", None))
        self.actionMorphology_filter.setText(_translate("EAMViewer", "morphology filter", None))
        self.actionLaplacian.setText(_translate("EAMViewer", "laplacian", None))
        self.actionLines.setText(_translate("EAMViewer", "lines", None))
        self.actionCircles.setText(_translate("EAMViewer", "circles", None))
        self.actionCorners.setText(_translate("EAMViewer", "corners", None))
        self.actionSelect.setText(_translate("EAMViewer", "select", None))
        self.actionOpen.setText(_translate("EAMViewer", "open", None))
        self.actionDelete_chosen_elements.setText(_translate("EAMViewer", "delete chosen elements", None))
        self.actionSave_database.setText(_translate("EAMViewer", "save database ", None))
        self.actionOn_ROI.setText(_translate("EAMViewer", "on roi", None))
        self.actionOn_canny.setText(_translate("EAMViewer", "on canny", None))
        self.actionOpen_tm_tab.setText(_translate("EAMViewer", "open tm tab", None))
        self.actionOpen_cam.setText(_translate("EAMViewer", "open cam", None))
        self.actionOn_video.setText(_translate("EAMViewer", "on video", None))

from eventsqgraphicsview import EventsQGraphicsView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EAMViewer = QtGui.QMainWindow()
    ui = Ui_EAMViewer()
    ui.setupUi(EAMViewer)
    EAMViewer.show()
    sys.exit(app.exec_())

